### ISSUE TITLE
Makefile issue

### ISSUE THREAD

**Issue by HegManga** [AlexHalogen/MC_DungeonFinder#1]
In makefile:
utils/callbacks.o: utils/callbacks.c
NOT
utils/callbacks.o: utils/callbacks."h"

I had compilation problems with "invalid format callbacks.o"

**Comment by AlexHalogen** [comment]
Hi, thanks for the issue!
I've pushed a fix to correct this error. 

I wrote this a long time ago when I didn't know much about CI, testing kind of stuff, so, mistakes like this happen.
Sorry for the confusion, and please let me know if it still doesn't work.

**Comment by HegManga** [comment]
Compiled! 
I did a little test and everything looks ok. 

Nice idea. I really like that it's written in C! ;)

**Comment by AlexHalogen** [comment]
Glad that helps!
